#!/bin/bash

# Copyright 2016 Mycroft AI, Inc.
#
# This file is part of Mycroft Core.
#
# Mycroft Core is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Mycroft Core is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Mycroft Core.  If not, see <http://www.gnu.org/licenses/>.


# @author Augusto Monteiro
#
# This script assists in the installation and management of
# skills loaded from Github.  

set -e

mycroft_skill_folder="/opt/mycroft/skills"
mycroft_virtualenv=~/.virtualenvs/mycroft/bin/activate

echo "#######  Mycroft Skill Manager #######"

function help() {
	echo "msm: Mycroft Skill Manager"
	echo -e "     Copyright (c) 2017 Mycroft AI, Inc.  All rights reserved.\n"
	echo "usage: msm install <repository> or <name>"
	echo "     Installs the given Skill into the /opt/mycroft/skills directory"
	echo "     where <repository> is the address of the skill in Github."
	echo -e "example: msm install https://github.com/ethanaward/demo_skill.git\n"
}


function goto_skills_dir {
        if [ ! -d $mycroft_skill_folder ]; then
            echo "Couldn't install skill, $mycroft_skill_folder does not exist"
            exit 1
        fi
        cd $mycroft_skill_folder
}

function install() {
cd "${mycroft_skill_folder}"
if [[ "${vwrap}" == 'false' ]] ; then
    echo "Missing virtualwrapper, cowardly refusing to install skills."
    return 5
fi
# loop through list of arguments
while [[ $# -gt 0 ]] ; do
  cd "${mycroft_skill_folder}"
  iskill="${1}";
  shift;
  echo "Attempting to install ${iskill}..."
  if [[ "${iskill}" == "git@"* || "${iskill}" == "https://"* || "${iskill}" == "http://"* ]]; then
    repo="${iskill}"
  else
    skills=$(list | grep -n 'submodule' | sed 's/[[:space:]]//g' | sed 's/\[submodule"//g' | sed 's/"\]//g')
    exact_match=$(echo "$skills" | grep -i ".*:${iskill}$")
    skill=$(echo "$skills" | grep -i ".*:.*${iskill}.*")
    if [[ ! -z "${exact_match}" ]]; then
      skill=${exact_match}
    fi
    git_line=$(echo "$skill" | sed 's/\:.*//')

    if [[ "${skill}" ==  *$'\n'* ]]; then
      echo -e "Your search has multiple choices\n\n$skill" | sed 's/.*://g'
      return 3
    else
      if [[ -z "${git_line}" ]]; then
        echo "A ${iskill} skill was not found"
        return 3
      fi
      repo_line=$(($git_line + 2))
      repo=$(list | sed -n $repo_line'{p;q;}' | sed 's/[[:space:]]//g' | sed 's/url=//g')
    fi
  fi
  git_name=$(echo "${repo}" | sed 's/.*\///')
  name=$(echo "$git_name" | sed 's/.git//')
  if [[ -d "${mycroft_skill_folder}/${name}" ]] ; then
    echo "Skill appears to exist already. Perhaps you meant to use update?"
    continue 169
  fi
  echo "Cloning repository"
  git clone "${repo}" >> /dev/null
  if ! cd "${name}" ; then
    echo "Unable to access directory ${name}!"
    return 102
  fi
  if [[ "${picroft}" == "true" ]] ; then
    if ! sudo chown -R mycroft:mycroft "${mycroft_skill_folder}/${name}" ; then
      echo "Unable to chown install directory ${name}!"
      return 123
    fi
  fi
  if [[ -f "requirements.txt" ]]; then
    echo "Installing libraries requirements"
    if [[ "${picroft}" == 'false' ]]; then
      if [[ "${VIRTUAL_ENV}" =~ .mycroft$ ]] ; then
        if ! pip install -r requirements.txt ; then
          echo "Unable to install requirements for skill ${iskill}!"
          return 121
        fi
      else
        if workon mycroft ; then
          if ! pip install -r requirements.txt ; then
            echo "Unable to install requirements for skill ${iskill}!"
            deactivate mycroft
            return 121
          fi
        else
          echo "Unable to activate mycroft virtualenv!"
          deactivate
          return 120
        fi
      fi
    else
      if ! sudo pip install -r requirements.txt ; then
        echo "Unable to install requirements for skill ${iskill}!"
        return 121
      fi
    fi
  fi
  echo "The ${iskill} skill has been installed!"
done

}

function update() {
cd "${mycroft_skill_folder}"
for d in $(find "${mycroft_skill_folder}" -mindepth 1 -maxdepth 1 -type d |grep -v '.git'$ ); do
  if git -C "$d" rev-parse --git-dir > /dev/null 2>&1; then
    cd "${d}"
    UPSTREAM=${1:-'@{u}'}
    LOCAL=$(git rev-parse @)
    REMOTE=$(git rev-parse "$UPSTREAM")
    BASE=$(git merge-base @ "$UPSTREAM")

    if ! grep -q '.pyc'$ .git/info/exclude; then
      echo "*.pyc" >> .git/info/exclude
    fi

    # Checking if the repo isn't dirty or have commits to push
    if [[ (-z $(git status --porcelain --untracked-files=no)) && !($LOCAL != $REMOTE && $REMOTE = $BASE) ]]; then
      git fetch
      git reset --hard origin/master
      rm -f *.pyc
    fi
  fi
done
}

function install_defaults() {
	skills=( "alarm" "audio-record" "configuration" "date-time" "desktop-launcher" "ip" "joke" "hello-world" "media" "npr-news" "naptime" "pairing" "personal" "reminder" "installer" "singing" "speak" "spelling" "stop" "stock" "volume" "weather" "wiki" "wolfram-alpha" "mark1-demo" )
	for i in "${skills[@]}"
	do
		if [ ! -d "$mycroft_skill_folder/skill-$i" ]; then
			install "" "https://github.com/MycroftAI/skill-$i.git"	
		fi
	done
	update
	echo "Installed!"
	exit 0
}

function list() {
	curl -s "https://raw.githubusercontent.com/MycroftAI/mycroft-skills/master/.gitmodules" | grep 'submodule "' | sed 's/\[submodule "//g'| sed 's/"\]//g'
}

if [ "$1" = "install" ]; then
	install $*
elif [ "$1" = "list" ]; then
	echo -e "Searching...\n"
	list 
elif [ "$1" = "update" ]; then
	update 
elif [ "$1" = "default" ]; then
	install_defaults 
else
	help
fi

